import { Toaster } from "@/components/ui/sonner";
import { SessionConfig } from "@/config/provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <SessionConfig>
        <html lang="en">
          <body className={` ${geistMono.className} antialiased`}>
            {children}
          </body>
          <Toaster position="top-center" />
        </html>
      </SessionConfig>
    </>
  );
}
